filebeat.inputs:
  - type: log
    paths:
      - /app/logs/*.log
    json.keys_under_root: true
    json.add_error_key: true
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  index: "logs-sidecar-%{+yyyy.MM.dd}"

setup.template.name: "logs-sidecar"
setup.template.pattern: "logs-sidecar-*"
setup.kibana:
  host: "http://kibana:5601"
