filebeat.inputs:
  - type: log
    paths:
      - /var/log/nginx/*.log
      - /var/www/storage/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
